name: SupportChat
author: YonasCode
version: 1.0-SNAPSHOT
description: Support Live Chat System.
main: de.YonasCode.SupportChat.Main

commands:
     support:
          description: Support System Main Command.
          default: op
          usage: '/<command> "message"|list|accept [player]|clear|leave|close <player> [note]|delete'
          aliases: support, ask